backend:
  name: git-gateway
  branch: main # Or the default branch of your repository

media_folder: "static/images/uploads" # Where uploaded images are stored
public_folder: "/images/uploads" # URL path to the images

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
